import{r as e,g as n}from"./CNBxHfNM.js";var t,r,u,o,i={exports:{}},a={},c={exports:{}},s={};function f(){return r||(r=1,c.exports=function(){if(t)return s;t=1;var n=e(),r="function"==typeof Object.is?Object.is:function(e,n){return e===n&&(0!==e||1/e==1/n)||e!=e&&n!=n},u=n.useState,o=n.useEffect,i=n.useLayoutEffect,a=n.useDebugValue;function c(e){var n=e.getSnapshot;e=e.value;try{var t=n();return!r(e,t)}catch(u){return!0}}var f="undefined"==typeof window||void 0===window.document||void 0===window.document.createElement?function(e,n){return n()}:function(e,n){var t=n(),r=u({inst:{value:t,getSnapshot:n}}),s=r[0].inst,f=r[1];return i((function(){s.value=t,s.getSnapshot=n,c(s)&&f({inst:s})}),[e,t,n]),o((function(){return c(s)&&f({inst:s}),e((function(){c(s)&&f({inst:s})}))}),[e]),a(t),t};return s.useSyncExternalStore=void 0!==n.useSyncExternalStore?n.useSyncExternalStore:f,s}()),c.exports}
/**
 * @license React
 * use-sync-external-store-shim/with-selector.production.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */const l=n((o||(o=1,i.exports=function(){if(u)return a;u=1;var n=e(),t=f(),r="function"==typeof Object.is?Object.is:function(e,n){return e===n&&(0!==e||1/e==1/n)||e!=e&&n!=n},o=t.useSyncExternalStore,i=n.useRef,c=n.useEffect,s=n.useMemo,l=n.useDebugValue;return a.useSyncExternalStoreWithSelector=function(e,n,t,u,a){var f=i(null);if(null===f.current){var v={hasValue:!1,value:null};f.current=v}else v=f.current;f=s((function(){function e(e){if(!c){if(c=!0,o=e,e=u(e),void 0!==a&&v.hasValue){var n=v.value;if(a(n,e))return i=n}return i=e}if(n=i,r(o,e))return n;var t=u(e);return void 0!==a&&a(n,t)?(o=e,n):(o=e,i=t)}var o,i,c=!1,s=void 0===t?null:t;return[function(){return e(n())},null===s?void 0:function(){return e(s())}]}),[n,t,u,a]);var S=o(e,f[0],f[1]);return c((function(){v.hasValue=!0,v.value=S}),[S]),l(S),S},a}()),i.exports));export{l as u};
